# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DSC 40A
description: DSC 40A, Summer 2024 at UC San Diego
tagline: Theoretical Foundations of Data Science I
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dsc-courses.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: DSC 40A course staff
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: bluecsd
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  ðŸ™‹ Ed:
    - "https://edstem.org/us/courses/61623/discussion/"
  ðŸ’¯ Gradescope:
    - "https://www.gradescope.com/courses/814891/"
  ðŸ’ª Practice:
    - "https://practice.dsc40a.com"
  ðŸ¤” Lecture Questions:
    - "https://docs.google.com/forms/d/e/1FAIpQLSfEaSAGovXZCk_51_CVI587CcGW1GZH1w4Y50dKDzoLEX3D4w/viewform"
  ðŸŽ¥ Podcast:
    - "https://podcast.ucsd.edu/watch/s224/dsc40a_a00"
footer_content:

# Collections for website data
collections:
  staffers:
  advicers:
  staffersnobio:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ""
      type: staffers
    values:
      layout: staffer
      subpath: "/assets/images/"
  - scope:
      path: ""
      type: advicers
    values:
      layout: advicer
      subpath: "/assets/images/"
  - scope:
      path: ""
      type: staffersnobio
    values:
      layout: staffer_no_bio
      subpath: "/assets/images/"
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag

# callouts
callouts:
  red:
    title:
    color: red
  yellow:
    title:
    color: yellow
  green:
    title: ""
    color: green
